Document: rigol-dsa815
Title: Debian rigol-dsa815 Manual
Author: <insert document author here>
Abstract: This manual describes what rigol-dsa815 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rigol-dsa815/rigol-dsa815.sgml.gz

Format: postscript
Files: /usr/share/doc/rigol-dsa815/rigol-dsa815.ps.gz

Format: text
Files: /usr/share/doc/rigol-dsa815/rigol-dsa815.text.gz

Format: HTML
Index: /usr/share/doc/rigol-dsa815/html/index.html
Files: /usr/share/doc/rigol-dsa815/html/*.html
